### PR TITLE
Fix footer resizing on small viewport

### LINKED ISSUE #222: Footer is not responsive

### PR DESCRIPTION
**Pull request by chenglou**
Fixes #222

Untested but finger crossed? Manually changed the CSS live

before: 
screenshot 2014-09-05 11 14 19

after: 
screenshot 2014-09-05 11 14 13

### CODE REVIEW

**Comment by dellsystem** [comment]
Thanks!

**Comment by chenglou** [comment]
Hah, I've been tricked by that close button myself =).

**Comment by dellsystem** [comment]
Haha yeah, I kind of just randomly clicked it without actually reading what it said ... oops

**Comment by dellsystem** [comment]
Wait, I totally forgot the reason I had `position: absolute;` in the first place. It's for sticky footer purposes (otherwise, on short pages, the footer goes below the viewport). I'm going to revert it for now - I'm planning on doing a complete design overhaul eventually anyway.

**Pull request merged**
