### PR TITLE
News app

### PR DESCRIPTION
**Pull request by kimpettersen**

### CODE REVIEW

**Comment by dellsystem** [comment]
Hey Kim, sorry for taking so long to get to this. Are you sure your fork has all your commits? I just pulled your changes and it doesn't look like there's anything within the blog application (except the pagination app) or any changes to urls.py. Let me know if there's anything I can do.

**Comment by kimpettersen** [comment]
Hey,
I just saw that it was wrong. But i learned a better way to make the blog
things a few days ago. I can redo it and update at some point this week and
commit?

Kim

**Comment by dellsystem** [comment]
Sounds good, thanks Kim.

**Comment by kimpettersen** [comment]
I just submitted the blog thing. It is very basic and lets you: Create, edit, delete a blog post. I have not styled it yet, but if this is something you can use I will do it.
Should I also add the posibility to add comments? What about authorization? Y

**Comment by dellsystem** [comment]
Sorry for the delay again. The create and edit functionality should really be part of the admin interface. Do you know how to do that? If you don't think you can do this then I can take care of it - let me know.

**Pull request closed without merging**
